Provide upgrade handling from version 1.03 in etch. Do not depend on redhat-cluster-modules, have gfs-tools and gnbd-client recommend it instead.
git-svn-id: svn://svn.debian.org/svn/kernel/dists/trunk@9994 510b9475-24dd-0310-9b6c-e0eefe99d49f

diff --git a/redhat-cluster/redhat-cluster/debian/cman.preinst b/redhat-cluster/redhat-cluster/debian/cman.preinst
--- a/redhat-cluster/redhat-cluster/debian/cman.preinst
+++ b/redhat-cluster/redhat-cluster/debian/cman.preinst
@@ -2,17 +2,20 @@
 
 set -e
 
-. /usr/share/debconf/confmodule
-db_version 2.0
-
-if [ -n "$2" ] && dpkg --compare-versions "$2" lt 2.0; then
-	db_get cman/upgrade-from-old
-	ANSWER="$RET"
-	db_fset cman/upgrade-from-old seen_in_2.0_upgrade false
-	if [ "$ANSWER" = false ]; then
-		exit 1
-	fi
-fi
+case $1 in
+	upgrade)
+		. /usr/share/debconf/confmodule
+		db_version 2.0
+		if dpkg --compare-versions "$2" lt 2.0 ; then
+			db_fset cman/upgrade-warning seen_in_2.0_upgrade false
+			db_get cman/upgrade-warning
+			if [ "$RET" = "false" ] ; then
+				echo "aborting cman installation."
+				exit 1
+			fi
+		fi
+	;;
+esac
 
 #DEBHELPER#
 
