Explicitly ignore -r (but why?) and treat undeclared options as an internal getopt error.
git-svn-id: svn://svn.debian.org/svn/kernel/dists/trunk@4507 510b9475-24dd-0310-9b6c-e0eefe99d49f

diff --git a/utils/initramfs-tools/mkinitramfs b/utils/initramfs-tools/mkinitramfs
--- a/utils/initramfs-tools/mkinitramfs
+++ b/utils/initramfs-tools/mkinitramfs
@@ -36,6 +36,10 @@ while true ; do
 		keep="y"
 		shift
 		;;
+	-r)
+		# ignore (FIXME: manpage says differently?!?)
+		shift 2
+		;;
 	--supported-host-version)
 		supported_host_version="$2"
 		shift 2
@@ -47,6 +51,10 @@ while true ; do
 	--)
 		shift
 		break
+		;;
+	*)
+		echo "Internal error!" >&2
+		exit 1
 		;;
 	esac
 done
